api/urls.py
"""
URL map for API module.
"""

from django.conf.urls import url, patterns, include

from api.views import (
    SummonerList,
    SummonerDetail,
    ChampionList,
    ChampionDetail,
    ItemList,
    ItemDetail,
    SummonerSpellList,
    SummonerSpellDetail,
    PlayerList,
    PlayerDetail,
    RawStatList,
    RawStatDetail,
    GameList,
    GameDetail,
    LeagueList,
    LeagueDetail,
    LeagueEntryList,
    LeagueEntryDetail,
    TeamList,
    TeamDetail,
    RosterList,
    RosterDetail,
    TeamMemberInfoList,
    TeamMemberInfoDetail,
    PlayerStatList,
    PlayerStatDetail,
    api_root)

# TODO: Consider allowing lookup by ID (check for number instead of \w+)
# TODO: Consider separating out summoner-list and summoner-region-list classes (same name in browseable API)
# TODO: Add action prefixes to endpoints such as `by-id`, `by-name`, etc.
urlpatterns = patterns('api',
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^task_state$', 'views.get_task_state', name='task_state'),

    # Note: trailing slashes
    url(r'^$', api_root),

    url(r'^summoners$', SummonerList.as_view(), name='summoner-list'),
    url(r'^summoners/(?P<region>\w+)$', SummonerList.as_view(), name='summoners-region-list'),
    url(r'^summoners/(?P<region>\w+)/(?P<name>\w+( *\w+)*)$', SummonerDetail.as_view(), name='summoners-detail'),

    url(r'^champions$', ChampionList.as_view(), name='champion-list'),
    url(r'^champions/(?P<name>\w+)$', ChampionDetail.as_view(), name='champion-detail'),

    url(r'^items$', ItemList.as_view(), name='item-list'),
    url(r'^items/(?P<name>\w+( *\w+)*)$$', ItemDetail.as_view(), name='item-detail'),

    url(r'^spells$', SummonerSpellList.as_view(), name='spell-list'),
    url(r'^spells/(?P<name>\w+( *\w+)*)$$', SummonerSpellDetail.as_view(), name='spell-detail'),

    url(r'^players$', PlayerList.as_view(), name='player-list'),
    url(r'^players/(?P<name>\w+( *\w+)*)$', PlayerDetail.as_view(), name='player-detail'),

    url(r'^stats$', RawStatList.as_view(), name='stat-list'),
    url(r'^stats/(?P<game_id>\d+$)', RawStatDetail.as_view(), name='stat-detail'),

    url(r'^games$', GameList.as_view(), name='game-list'),
    url(r'^games/(?P<region>\w+)/(?P<game_id>\d+$)', GameDetail.as_view(), name='game-detail'),
    # \w matches digits, so it is important that this comes after the detail view, which uses game_id for lookup!
    url(r'^games/(?P<region>\w+)/(?P<name>\w+( *\w+)*)$', GameList.as_view(), name='game-region-name-list'),

    url(r'^leagues$', LeagueList.as_view(), name='league-list'),
    url(r'^leagues/(?P<region>\w+)$', LeagueList.as_view(), name='league-region-list'),
    url(r"^leagues/(?P<region>\w+)/(?P<queue>\w+)$", LeagueList.as_view(), name='league-region-queue-list'),
    url(r"^leagues/(?P<region>\w+)/(?P<queue>\w+)/(?P<tier>\w+)$", LeagueList.as_view(), name='league-region-queue-tier-list'),
    url(r"^leagues/(?P<region>\w+)/(?P<queue>\w+)/(?P<tier>\w+)/(?P<name>\w+('* *\w+)*)$", LeagueDetail.as_view(), name='league-detail'),

    url(r'^league-entries$', LeagueEntryList.as_view(), name='league-entry-list'),
    url(r'^league-entries/(?P<region>\w+)$', LeagueEntryList.as_view(), name='league-entry-region-list'),
    # Retrieve by player_or_team_id.
    url(r'^league-entries/(?P<region>\w+)/(?P<id>(-*\w+)*)$', LeagueEntryDetail.as_view(), name='league-entry-detail'),

    url(r'^teams$', TeamList.as_view(), name='team-list'),
    url(r'^teams/(?P<region>\w+)$', TeamList.as_view(), name='team-region-list'),
    # List by std_name.
    url(r'^teams/(?P<region>\w+)/by-member/(?P<member_name>\w+( *\w+)*)$', TeamList.as_view(), name='team-by-member-name-list'),
    # Retrieve by full_id.
    url(r'^teams/(?P<region>\w+)/by-team-id/(?P<full_id>TEAM(-*\w+)*)$', TeamDetail.as_view(), name='team-detail'),

    url(r'^rosters$', RosterList.as_view(), name='roster-list'),

    url(r'^teammemberinfo$', TeamMemberInfoList.as_view(), name='teammemberinfo-list'),

    url(r'^playerstats$', PlayerStatList.as_view(), name='playerstat-list'),
    url(r'^playerstats/(?P<region>\w+)/(?P<name>\w+( *\w+)*)$', PlayerStatDetail.as_view(), name='playerstat-detail'),

)

lol_stats/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    # Don't care about API versioning b/c it will only be called by our domain's AJAX.
    url(r'^api/', include('api.urls')),
    url(r'^summoner/', include('summoner.urls')),
    url(r'^item/', include('item.urls')),

    #url(r'^items/', 'api.views.view_items', name='view_items'),
)

summoner/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('summoner',
    # These regex are not robust.
    # This requires a string after summoner_info/ (consider pointing to blank search page when no arg)
    # url(r'^info/(?P<summoner_name>\w+( \w+)*$)', 'views.summoner_info', name='summoner_info'),
    # url(r'^async_summoner_info/', 'views.async_summoner_info', name='async_summoner_info'),
    # url(r'^ajax_summoner_info/', 'views.ajax_summoner_info', name='ajax_summoner_info'),
    # url(r'^recent/(?P<summoner_name>\w+( \w+)*$)', 'views.recent_games', name='recent_games'),
    # url(r'^do_task$', 'views.ajax_query_start', name='do_task'),
    url(r'^ajax_query_start$', 'views.ajax_query_start', name='ajax_query_start'),
    # url(r'^sum_info$', 'views.summoner_info', name='base_summoner_info'),
)

api/models.py
"""
Django models for lol_stats project.
"""

import time

import inflection
from django.db import models
from django.core.exceptions import ObjectDoesNotExist

# TODO: Set PKs to extant fields, if possible.


class Summoner(models.Model):
    """Maps to Riot API summoner DTO.

    Also contains timestamp for when object was last updated.
    """
    summoner_id = models.BigIntegerField()
    # Names "should" be 16 chars, but sometimes we get weird names (ex. "IS141dca1d0484dcf8adc09")
    name = models.CharField(max_length=24)
    std_name = models.CharField(max_length=24)  # This is `name` as lowercase with spaces stripped.
    profile_icon_id = models.IntegerField()
    revision_date = models.BigIntegerField()
    summoner_level = models.IntegerField()  # 'long' in DTO, but we know it's <= 30
    region = models.CharField(max_length=4)
    last_update = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    class Meta:
        """These fields, taken together, ensure no duplicates are created."""
        unique_together = ('summoner_id', 'region')


class Champion(models.Model):
    """Maps to Riot API champion DTO."""
    champion_id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=32)
    name = models.CharField(max_length=32)
    key = models.CharField(max_length=32)

    def __unicode__(self):
        return self.name


class Item(models.Model):
    """Maps to Riot API item DTO."""
    item_id = models.IntegerField(primary_key=True)
    description = models.CharField(max_length=1024)
    name = models.CharField(max_length=64)
    plain_text = models.CharField(max_length=256, blank=True, null=True)
    group = models.CharField(max_length=64, blank=True, null=True)

    def __unicode__(self):
        return self.name


class SummonerSpell(models.Model):
    """Maps to Riot API summonerSpell DTO."""
    spell_id = models.IntegerField(primary_key=True)
    summoner_level = models.IntegerField()
    name = models.CharField(max_length=16)
    key = models.CharField(max_length=32)
    description = models.CharField(max_length=256)

    def __unicode__(self):
        return u'%s' % self.name

## placeholder
#class Mastery(models.Model):
#    pass
#
## placeholder
#class Rune(models.Model):
#    pass
#
## placeholder
#class Realm(models.Model):
#    pass


#########
# GAMES #
#########


class Player(models.Model):
    """
    Maps to Riot API fellowPlayer DTO.

    fellowPlayer is related to match history query.
    """
    champion = models.ForeignKey(Champion)
    summoner = models.ForeignKey(Summoner)
    team_id = models.IntegerField()  # 100, 200
    participant_of = models.ForeignKey('Game')

    class Meta:
        ordering = ('team_id',)

    def __unicode__(self):
        return u'%s on %s (Team %d)' % (self.summoner, self.champion, self.team_id)

    def region(self):
        return self.participant_of.region


class RawStat(models.Model):
    """
    Maps to Riot API RawStats DTO.

    RawStats is related to match history query.
    """
    assists = models.IntegerField(blank=True, null=True)
    barracks_killed = models.IntegerField(blank=True, null=True)
    champions_killed = models.IntegerField(blank=True, null=True)
    combat_player_score = models.IntegerField(blank=True, null=True)
    consumables_purchased = models.IntegerField(blank=True, null=True)
    damage_dealt_player = models.IntegerField(blank=True, null=True)
    double_kills = models.IntegerField(blank=True, null=True)
    first_blood = models.IntegerField(blank=True, null=True)
    gold = models.IntegerField(blank=True, null=True)
    gold_earned = models.IntegerField(blank=True, null=True)
    gold_spent = models.IntegerField(blank=True, null=True)
    item0 = models.IntegerField(blank=True, null=True)
    item1 = models.IntegerField(blank=True, null=True)
    item2 = models.IntegerField(blank=True, null=True)
    item3 = models.IntegerField(blank=True, null=True)
    item4 = models.IntegerField(blank=True, null=True)
    item5 = models.IntegerField(blank=True, null=True)
    item6 = models.IntegerField(blank=True, null=True)
    items_purchased = models.IntegerField(blank=True, null=True)
    killing_sprees = models.IntegerField(blank=True, null=True)
    largest_critical_strike = models.IntegerField(blank=True, null=True)
    largest_killing_spree = models.IntegerField(blank=True, null=True)
    largest_multi_kill = models.IntegerField(blank=True, null=True)
    legendary_items_created = models.IntegerField(blank=True, null=True)  # Number of tier 3 items built.
    level = models.IntegerField(blank=True, null=True)
    magic_damage_dealt_player = models.IntegerField(blank=True, null=True)
    magic_damage_dealt_to_champions = models.IntegerField(blank=True, null=True)
    magic_damage_taken = models.IntegerField(blank=True, null=True)
    minions_denied = models.IntegerField(blank=True, null=True)
    minions_killed = models.IntegerField(blank=True, null=True)
    neutral_minions_killed = models.IntegerField(blank=True, null=True)
    neutral_minions_killed_enemy_jungle = models.IntegerField(blank=True, null=True)
    neutral_minions_killed_your_jungle = models.IntegerField(blank=True, null=True)
    nexus_killed = models.NullBooleanField(blank=True, null=True)  # Flag specifying if the summoner got the killing blow on the nexus.
    node_capture = models.IntegerField(blank=True, null=True)
    node_capture_assist = models.IntegerField(blank=True, null=True)
    node_neutralize = models.IntegerField(blank=True, null=True)
    node_neutralize_assist = models.IntegerField(blank=True, null=True)
    num_deaths = models.IntegerField(blank=True, null=True)
    num_items_bought = models.IntegerField(blank=True, null=True)
    objective_player_score = models.IntegerField(blank=True, null=True)
    penta_kills = models.IntegerField(blank=True, null=True)
    physical_damage_dealt_player = models.IntegerField(blank=True, null=True)
    physical_damage_dealt_to_champions = models.IntegerField(blank=True, null=True)
    physical_damage_taken = models.IntegerField(blank=True, null=True)
    quadra_kills = models.IntegerField(blank=True, null=True)
    sight_wards_bought = models.IntegerField(blank=True, null=True)
    spell_1_cast = models.IntegerField(blank=True, null=True)  # Number of times first champion spell was cast.
    spell_2_cast = models.IntegerField(blank=True, null=True)  # Number of times second champion spell was cast.
    spell_3_cast = models.IntegerField(blank=True, null=True)  # Number of times third champion spell was cast.
    spell_4_cast = models.IntegerField(blank=True, null=True)  # Number of times fourth champion spell was cast.
    summon_spell_1_cast = models.IntegerField(blank=True, null=True)
    summon_spell_2_cast = models.IntegerField(blank=True, null=True)
    super_monster_killed = models.IntegerField(blank=True, null=True)
    team = models.IntegerField(blank=True, null=True)  # redundant due to Game.team_id
    team_objective = models.IntegerField(blank=True, null=True)
    time_played = models.IntegerField(blank=True, null=True)
    total_damage_dealt = models.IntegerField(blank=True, null=True)
    total_damage_dealt_to_champions = models.IntegerField(blank=True, null=True)
    total_damage_taken = models.IntegerField(blank=True, null=True)
    total_heal = models.IntegerField(blank=True, null=True)
    total_player_score = models.IntegerField(blank=True, null=True)
    total_score_rank = models.IntegerField(blank=True, null=True)
    total_time_crowd_control_dealt = models.IntegerField(blank=True, null=True)
    total_units_healed = models.IntegerField(blank=True, null=True)
    triple_kills = models.IntegerField(blank=True, null=True)
    true_damage_dealt_player = models.IntegerField(blank=True, null=True)
    true_damage_dealt_to_champions = models.IntegerField(blank=True, null=True)
    true_damage_taken = models.IntegerField(blank=True, null=True)
    turrets_killed = models.IntegerField(blank=True, null=True)
    unreal_kills = models.IntegerField(blank=True, null=True)
    victory_point_total = models.IntegerField(blank=True, null=True)
    vision_wards_bought = models.IntegerField(blank=True, null=True)
    ward_killed = models.IntegerField(blank=True, null=True)
    ward_placed = models.IntegerField(blank=True, null=True)
    win = models.NullBooleanField(blank=True, null=True)  # Flag specifying whether or not this game was won.

    def __unicode__(self):
        return u'Stats for %s' % Game.objects.get(stats=self)

    def __iter__(self):
        """Generator that returns field names and values for each value that is not None."""
        for i in self._meta.get_all_field_names():
            if getattr(self, i) is not None:
                yield u'{}: {}'.format(inflection.humanize(i), getattr(self, i))

    def belongs_to(self):
        return Game.objects.get(stats=self).summoner_id

    def champion_played(self):
        return Game.objects.get(stats=self).champion_id

    def game_id(self):
        return Game.objects.get(stats=self).game_id

    def region(self):
        return Game.objects.get(stats=self).region

    def timestamp(self):
        return Game.objects.get(stats=self).create_date_str()


class Game(models.Model):
    """
    Maps to Riot API Game DTO.

    Instead of summonerId and championId, foreign keys to those objects are used.
    RawStat object is related to by these objects via 1-to-1.
    Player objects point to this to allow reverse-querying of match participants.

    To get a match history (QuerySet), given a region (R) and Summoner name (N):

    Game.objects.filter(summoner_id=Summoner.objects.filter(region=R).filter(name=N)

    Alternatively, given a Summoner object (S):

    S.game_set.all()
    """
    summoner_id = models.ForeignKey(Summoner)
    champion_id = models.ForeignKey(Champion)
    create_date = models.BigIntegerField()
    game_id = models.BigIntegerField()

summoner/models.py
from django.db import models

# Create your models here.

lol_stats/templates/summoner/async_summoner_info.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>AJAX Summoner Info</title>
    </head>
    <body>
        {% csrf_token %}
        <a href="#" id="go">Go!</a>

        <span id="summoner_id" data-to-query="299878"></span>

        <div id="summoner">
            <ul id="summoner_properties">
                <li id="summoner_id"></li>
                <li id="name"></li>
                <li id="profile_icon_id"></li>
                <li id="revision_date"></li>
                <li id="summoner_level"></li>
                <li id="last_update"></li>
            </ul>
        </div>

        <script src="{% static "js/jquery-2.1.1.js" %}"></script>
        <script>
            $(function() {
                console.log( "ready!" );

                // using jQuery
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = jQuery.trim(cookies[i]);
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }
                var csrftoken = getCookie('csrftoken');

                function csrfSafeMethod(method) {
                    // these HTTP methods do not require CSRF protection
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }
                $.ajaxSetup({
                    crossDomain: false, // obviates need for sameOrigin test
                    beforeSend: function(xhr, settings) {
                        if (!csrfSafeMethod(settings.type)) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });

                $("#summoner_properties").hide();

                $("#go").click(function(event) {
                    event.preventDefault();
                    event.stopPropagation();

                    var sum_id = $("#summoner_id").data("to-query");

                    //console.log(sum_id);

                    $.ajax({
                       type: "GET",
                       url: "/summoners/1/?format=json",
                       data: { summoner_id: sum_id,
                               csrfmiddlewaretoken: csrftoken }
                    }).done(function( data ) {
                                console.log(data);

                    });
                });
            });
        </script>
    </body>
</html>

lol_stats/templates/summoner/match_history.html
{% extends "base.html" %}
{% block content %}
    <h1>Match History</h1>

    Data for Summoner: {{summoner}}<br><br>

    {% for g in games %}
        <h2>Game {{forloop.counter0|add:"1"}}</h2>
        <h3>Participants</h3>
        {{g}}<br>
        {% for p in g.player_set.all %}
            {{ p.summoner.name }} on {{ p.champion }} (Team {{ p.team_id }})<br>
        {% endfor %}

        <h3>Meta Stats</h3>

        Create date: {{g.create_date_str}} (GMT)<br>
        Game ID: {{g.game_id}}<br>
        Game Mode: {{g.game_mode}}<br>
        Game Type: {{g.game_type}}<br>
        Sub-type: {{g.sub_type}}<br>
        Invalid: {{g.invalid}}<br>
        IP Earned: {{g.ip_earned}}<br>
        Level: {{g.level}}<br>
        Map ID: {{g.map_id}}<br>
        Spell 1: {{g.spell_1}}<br>
        Spell 2: {{g.spell_2}}<br>

        <h3>Stats</h3>
        {% for i in g.stats %}
            {{i}}<br>
        {% endfor %}

    {% endfor %}
{% endblock content %}

lol_stats/templates/summoner/summoner_base.html
{% extends "base.html" %}

{% block title %}Summoner{% endblock title %}

{% block content %}
    {% load staticfiles %}
    Get info on a summoner...<br>


    Region: <input type="text" id="query-region" name="region" />
    Name: <input type="text" id="query-name" name="name" />
    <button id="do-task" type="button">query</button>

    <p>Status: <span id="status"></span></p>

    <div id="summoner-info">
        <h3>Summoner Info</h3>
        ID: <span id="id"></span><br>
        Name: <span id="name"></span><br>
        Level: <span id="level"></span><br>
        Region: <span id="region"></span><br>
        Last Updated: <span id="last-updated"></span><br>
    </div>

    <script src="{% static "js/jquery-2.1.1.js" %}"></script>
    <script type="text/javascript">
        var sumData = 0;

        function showInfo() {
            $.ajax({
                // TODO: Get Django url tag to work with this, instead of constructing by hand.
                url: "/api/summoners/" + $("#query-region").val() + "/" + $("#query-name").val() + "/",
                type: "GET",
                success: function(data) {
                    sumData = data;
                    console.log(sumData);

                    $("#id").text(sumData.summoner_id);
                    $("#name").text(sumData.name);
                    $("#level").text(sumData.summoner_level);
                    $("#region").text(sumData.region);
                    $("#last-updated").text(sumData.last_update);
                    $("#summoner-info").show();
                }
            })
        }

        $("div#summoner-info").hide();
        var task_id = 'test';

        $('#do-task').click( function() {
            $.ajax({
                url: "{% url 'ajax_query_start' %}",
                type: "POST",
                data: { region: $("#query-region").val(),
                        name: $("#query-name").val() },
                success: function(data) {
                    task_id = data;
                    console.log(task_id);

                    // clear before using, in case of browser weirdness
                    if (timerID) {
                        clearInterval(timerID);
                    }

                    var timerID = setInterval( function() {
                        $.ajax({
                            url: "{% url 'task_state' %}",
                            type: "POST",
                            data: { task_id: task_id },
                            success: function(data){
                                $("#status").html(data);

                                // the task completed
                                if (data == "SUCCESS") {
                                    clearInterval(timerID);
                                    showInfo();
                                }
                                else if (data == "FAILURE") {
                                    clearInterval(timerID);
                                }
                            }
                        })
                    }, 100);
                }
            })
        });
    </script>

{% endblock content %}